require 'spec_helper'
require 'json'

# Unit tests for KafkaProxyRestClient::ProducerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProducerApi' do
  before do
    # run before each test
    @instance = KafkaProxyRestClient::ProducerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProducerApi' do
    it 'should create an instact of ProducerApi' do
      expect(@instance).to be_instance_of(KafkaProxyRestClient::ProducerApi)
    end
  end

  # unit tests for topics_topic_name_post
  #
  # Produce messages to a topic, optionally specifying keys or partitions for the messages. If no partition is provided, one will be chosen based on the hash of the key. If no key is provided, the partition will be chosen for each message in a round-robin fashion.  #  For the &#x60;&#x60;avro&#x60;&#x60; embedded format, you must provide information about schemas and the REST proxy must be configured with the URL to access the schema registry (&#x60;&#x60;schema.registry.connect&#x60;&#x60;). Schemas may be provided as the full schema encoded as a string, or, after the initial request may be provided as the schema ID returned with the first response.
  # @param topic_name Name of the topic to produce the messages to
  # @param body Data to send to the kafka topic.
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse200]
  describe 'topics_topic_name_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
