require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KafkaProxyRestClient::InlineResponse200Offsets
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InlineResponse200Offsets' do
  before do
    # run before each test
    @instance = KafkaProxyRestClient::InlineResponse200Offsets.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineResponse200Offsets' do
    it 'should create an instact of InlineResponse200Offsets' do
      expect(@instance).to be_instance_of(KafkaProxyRestClient::InlineResponse200Offsets)
    end
  end
  describe 'test attribute "partition"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "offset"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "error_code"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "error"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
