require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KafkaProxyRestClient::Offset
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Offset' do
  before do
    # run before each test
    @instance = KafkaProxyRestClient::Offset.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Offset' do
    it 'should create an instact of Offset' do
      expect(@instance).to be_instance_of(KafkaProxyRestClient::Offset)
    end
  end
  describe 'test attribute "partition"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "offset"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "error_code"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "error"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
