require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KafkaProxyRestClient::ProducerResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProducerResponse' do
  before do
    # run before each test
    @instance = KafkaProxyRestClient::ProducerResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProducerResponse' do
    it 'should create an instact of ProducerResponse' do
      expect(@instance).to be_instance_of(KafkaProxyRestClient::ProducerResponse)
    end
  end
  describe 'test attribute "offsets"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "key_schema_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "value_schema_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
