require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KafkaProxyRestClient::Record
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Record' do
  before do
    # run before each test
    @instance = KafkaProxyRestClient::Record.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Record' do
    it 'should create an instact of Record' do
      expect(@instance).to be_instance_of(KafkaProxyRestClient::Record)
    end
  end
  describe 'test attribute "key"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "partition"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
