=begin
#Kafka REST Proxy API

#An initial draft of the [Kafka REST Proxy API](https://github.com/confluentinc/kafka-rest).  ## Example JSON request   ``` POST /topics/test HTTP/1.1 Host: kafkaproxy.example.com Content-Type: application/vnd.kafka.json.v2+json Accept: application/vnd.kafka.json.v2+json, application/vnd.kafka+json, application/json {   \"records\": [     {       \"key\": \"somekey\",       \"value\": {\"foo\": \"bar\"}     },     {       \"value\": [ \"foo\", \"bar\" ],       \"partition\": 1     },     {       \"value\": 53.5     }   ] } ```  ## Example JSON response  ``` HTTP/1.1 200 OK Content-Type: application/vnd.kafka.json.v2+json {   \"key_schema_id\": null,   \"value_schema_id\": null,   \"offsets\": [     {       \"partition\": 2,       \"offset\": 100     },     {       \"partition\": 1,       \"offset\": 101     },     {       \"partition\": 2,       \"offset\": 102     }   ] } ``` 

OpenAPI spec version: 0.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'

describe KafkaProxyRestClient::Configuration do
  let(:config) { KafkaProxyRestClient::Configuration.default }

  before(:each) do
    # uncomment below to setup host and base_path
    #require 'URI'
    #uri = URI.parse("https://localhost")
    #KafkaProxyRestClient.configure do |c|
    #  c.host = uri.host
    #  c.base_path = uri.path
    #end
  end

  describe '#base_url' do
    it 'should have the default value' do
      # uncomment below to test default value of the base path
      #expect(config.base_url).to eq("https://localhost")
    end

    it 'should remove trailing slashes' do
      [nil, '', '/', '//'].each do |base_path|
        config.base_path = base_path
        # uncomment below to test trailing slashes
        #expect(config.base_url).to eq("https://localhost")
      end
    end
  end
end
